jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: ""
      password: ""
      port: 5432
      dbname: jaffle_shop
      schema: dwh
      threads: 4
